# - name: 'Install python2 (ansible requires)'
#   raw: sudo apt-get -y install python

- name: Update apt cache and install python3
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      # - python3-venv
    state: latest
    update_cache: True

# - name: Switching to Python3
#   pip:
#     name: boto
#     virtualenv: /tmp/py3
#     virtualenv_command: /usr/bin/python3 -m venv
