---
- hosts: all
  become: true
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
  - vars.yml

  pre_tasks:
    # - name: 'Install python2 (ansible requires)'
    #   raw: sudo apt-get -y install python
    - name: Populate /etc/environment
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items: "{{environment_vars}}"

  roles:
  - role: apt_update
  - role: public_key
  - role: jdk
  - role: gitlab
  # - role: docker

  tasks:
