- name: "Waiting for Jenkins to come up"
  uri:
    url: "{{ jenkins_url }}/cli"
    status_code: 200
    force_basic_auth: yes
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
