- name: Update python3
  apt:
    name: ['python3-pip']
    state: latest

- name: Install python3 packages
  pip:
    name: ['selenium']
    state: latest

- name: Install Selenium
  apt: name=firefox,xvfb state=present

- name: "Check if Geckon is already installed."
  stat: path=/usr/bin/geckodriver
  register: geckon_file

- name: Downloading geckon driver
  shell: |
    cd /tmp
    wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    tar -xvzf geckodriver*
    chmod +x geckodriver
    mv geckodriver /usr/bin/
  when: not geckon_file.stat.exists
