- name: Copy public key to integration server
  copy: src=~/.ssh/id_rsa.pub dest=~vagrant/.ssh/me.pub
- shell: cat ~vagrant/.ssh/me.pub
  register: public_key
- lineinfile:
    path: ~vagrant/.ssh/authorized_keys
    line: "{{public_key.stdout}}"

- name: Create jenkins ssh folder
  file:
    path: /ssh
    state: directory
    mode: 0777
- name: Generate new keys (for connecting to docker via Jenkinsfile)
  shell: if [ ! -f /ssh/id_rsa ]; then ssh-keygen -C '' -t rsa -N '' -f /ssh/id_rsa && chmod 644 /ssh/id_rsa ; fi
