- name: Add Artifactory
  shell: |
    export JFROG_HOME=/opt/jfrog
    rm -rf $JFROG_HOME
    mkdir -p $JFROG_HOME/artifactory/var/etc/
    touch $JFROG_HOME/artifactory/var/etc/system.yaml
    chown -R 1030:1030 $JFROG_HOME/artifactory/var
    docker rm -f artifactory &>/dev/null
    docker run --name artifactory -v $JFROG_HOME/artifactory/var/:/var/opt/jfrog/artifactory -d -p 8021:8081 -p 8022:8082 docker.bintray.io/jfrog/artifactory-oss:latest
